### ISSUE TITLE
Add a new theme to the project.

### ISSUE THREAD

**Issue by abel-otegbola** [abel-otegbola/clock-app#1]
#1 Open up index.html, Add your own theme to the lists.
      - Add your data-theme name
      - Use fontawesome icon name to add your icon
![Screenshot_20221015-100813](https://user-images.githubusercontent.com/59369762/195978869-2b699361-f111-43fc-ae51-539784da7503.png)

#2 Open the theme.css and Style your theme using the data-theme you set. Forexample
``` 
article[data-theme="wooden"] .clock {
   // Your styles
}
```

#3 Optional. You can also style the dark version of your theme at the darkmode.css using  .dark

Looking forward to the awesome theme you will create.

**Comment by Tatwansh** [comment]
I would like to work on this issue.

**Comment by abel-otegbola** [comment]
Alright. I've assigned it to you. If you have any question. I'm always here to answer.

**Comment by abel-otegbola** [comment]
That was a very cool theme you added @Tatwansh  thank you for your contribution

**Comment by abel-otegbola** [comment]
Don't forget to  star🌟 the repo.
