### ISSUE TITLE
Enhancement and adding more features in footer and Nav bar

### ISSUE THREAD

**Issue by Aditya-chaki** [abel-otegbola/clock-app#18]
@abel-otegbola Kindly assign me this under Hacktoberfest 2022.

**Comment by abel-otegbola** [comment]
Alright. But can you state what you will be adding to the navbar and the footer?

**Comment by Aditya-chaki** [comment]
Sir I will add a SideNav bar which contains your theme and mode . And in footer ,  I will add the social media handles.

**Comment by abel-otegbola** [comment]
You can add the social media handles. Just the Twitter and github. But leave the sidenav bar. I prefer the one currently there.

**Comment by Aditya-chaki** [comment]
okay sir , I will work only on footer as per  your wish.

**Comment by abel-otegbola** [comment]
Also, you can put your own theme.

**Comment by abel-otegbola** [comment]
But the theme is optional. If you need any guide on adding any feature, I'll always be here to guide.

**Comment by Aditya-chaki** [comment]
Sir, can i remove social media handles from nav bar?

**Comment by abel-otegbola** [comment]
That will make the topbar look empty. Please just leave it there. If you have any suggestions for features we can add to the topbar, it's welcomed.

**Comment by Aditya-chaki** [comment]
Sir , I can add 'contact us' and 'about' features in place of that icons.

**Comment by abel-otegbola** [comment]
That's not necessary. Just add the social media handles to the footer

**Comment by Aditya-chaki** [comment]
Sir,I submitted my PR , please review it.
