### ISSUE TITLE
Styling the neon clock.

### ISSUE THREAD

**Issue by hunted-Rising** [abel-otegbola/clock-app#20]
I would love to style the neon clock ring and fingers in such a way that they change color using animation.

**Comment by abel-otegbola** [comment]
Cool. Go ahead @Ericchuk

**Comment by hunted-Rising** [comment]
alright

**Comment by abel-otegbola** [comment]
Hi @Ericchuk I just want to suggest that since the roman numerals for the neon is a png image, an easy way to achieve the animation is to use the filter: hue-rotate

**Comment by hunted-Rising** [comment]
yeah
