### ISSUE TITLE
Proposed responsiveness for tablet.

### ISSUE THREAD

**Issue by hunted-Rising** [abel-otegbola/clock-app#29]
Good day,
While writing the animation for neon, I had the webpage in a tablet for on my laptop and i discovered that the webpage just compresses to one side, while more can be done to transform that, I am proposing that the sidebar becomes the navbar with the night mode and dark mode at the top and the differen clock theme at the bottom of the dark and light mode. 
This gives the clock enough spacing and also make the webpage look pleasing in tablet format.

**Comment by abel-otegbola** [comment]
Hi @Ericchuk this project only allows one pull request per person. I really appreciate that you want to contribute as much as you can to the project.

**Comment by hunted-Rising** [comment]
alright, you can assign it to someone else

**Comment by Utkarshsharma1234** [comment]
Can you please assign this issue to me? Can i work on this project.
