### ISSUE TITLE
separate buttons for mode and background of clock 

### ISSUE THREAD

**Issue by ritika21-code** [abel-otegbola/clock-app#38]
we should have separate buttons for the mode and background of the clock. there needs to be alignment between items.

**Comment by abel-otegbola** [comment]
I don't understand what you are saying. There are different buttons for the modes already. And what alignment is that?

**Comment by ritika21-code** [comment]
Merging the dark mode and simple mode button and creating a different button under all the filters will be there.

**Comment by abel-otegbola** [comment]
Alright. But can you make it look like this
![Screenshot_20221017-151201](https://user-images.githubusercontent.com/59369762/196200012-5bcf377d-df3f-427d-b572-e9d8aa624823.png)
Instead of dark and black, It will be light and dark

**Comment by ritika21-code** [comment]
Yes

**Comment by abel-otegbola** [comment]
Alright. I've assigned it to you.

**Comment by abel-otegbola** [comment]
I can always assist you If you are having issues with the implementation.

**Comment by hiteshdate** [comment]
Hello @abel-otegbola I want to work on this issue for making separate buttons for  mode and background of clock , Please assign me this issue.

**Comment by abel-otegbola** [comment]
Hi @hiteshdate  
@ritika21-code is already working on it. But if the current person handling it can't get it done, I'll assign it to you

**Comment by ritika21-code** [comment]
I have completed the task

**Comment by hiteshdate** [comment]
> Hi @hiteshdate @ritika21-code is already working on it. But if the current person handling it can't get it done, I'll assign it to you

ok I am always ready for making it better please let me know if any issue. Thank you

**Comment by abel-otegbola** [comment]
Hi @hiteshdate the task is completed but you can always create a new issue for any feature you want to add to the project. It can be a new theme or styling of any part of the project.
