### ISSUE TITLE
adding favicon and new theme

### ISSUE THREAD

**Issue by subrato3** [abel-otegbola/clock-app#5]
I can add a favicon for the title tab for the page and 1/2 new themes to the project

**Comment by abel-otegbola** [comment]
Go ahead @subrato3 all contributions are accepted.

**Comment by TenzinNsut** [comment]
Hey abel-otegbola, I can work on this issue.

**Comment by abel-otegbola** [comment]
Hi @TenzinNsut  you can add a theme to the clock also.

**Comment by abel-otegbola** [comment]
> Hey abel-otegbola, I can work on this issue.

I've assigned you also. All you need to do is to just add a theme.

**Comment by TenzinNsut** [comment]
okay, I'll do that too.

**Comment by abel-otegbola** [comment]
@subrato3  will add the favicon and a theme.

**Comment by msabil443** [comment]
Hey abel-otegbola, I can work on this issue

**Comment by abel-otegbola** [comment]
> Hey abel-otegbola, I can work on this issue

Go ahead and add a new theme also

**Comment by abel-otegbola** [comment]
@TenzinNsut nice theme. But you should have left the favicon to @subrato3 

@subrato3 you can just add your own theme also.

**Comment by abel-otegbola** [comment]
We still have @msabil443 working on his own theme. Once he adds his own I will close the issue

**Comment by subrato3** [comment]
Ohh okay, my bad

**Comment by msabil443** [comment]
@abel-otegbola Thanks for considering my contribution. I have requested pull request.

**Comment by abel-otegbola** [comment]
Thanks to everyone for Contributing and the awesome themes you guys added. As this repo will only be accepting one pull request per person, you can check out other amazing repos of other people to continue hacking.
