### ISSUE TITLE
Add new theme to the project

### ISSUE THREAD

**Issue by abel-otegbola** [abel-otegbola/clock-app#56]
1. Open index.html and add your own theme in the list using the same format and including a data-theme. You can search fontawesome icons to add the name of your icon.
![Screenshot_20221015-100813](https://user-images.githubusercontent.com/59369762/196264524-97f83c15-dde6-43ab-8d98-614ab6dcb9b7.png)
2. Move to the themes.css to style your theme using the data-theme. Forexample
![Screenshot_20221015-100926~2](https://user-images.githubusercontent.com/59369762/196265274-67ddb000-f5bf-4a83-acbd-7b05c59bd495.png)

3. Optional. You can style the darkmode of your theme also by moving to the darkmode.css and follow same pattern as other themes.

**Comment by sayan404** [comment]
Want to do this work @abel-otegbola  ,,, asign me this issue

**Comment by abel-otegbola** [comment]
Go ahead @sayan404

**Comment by ritika21-code** [comment]
i want to add a new theme

**Comment by abel-otegbola** [comment]
Hi @ritika21-code I really appreciate your contributions but this project actually only allows one pull request per person. There are also other amazing projects you can work on 
Here is one https://github.com/Emilance/Javascript-Calculator-App or check through the issues page for good first issue projects.
