### ISSUE TITLE
adding new clock

### ISSUE THREAD

**Issue by tech0x10** [abel-otegbola/clock-app#60]

**Comment by abel-otegbola** [comment]
Hi @tech0x10 please go ahead and add your clock

**Comment by abel-otegbola** [comment]
You can follow these steps.
Add your theme in the list using the same format in index.html
![Screenshot_20221015-100813](https://user-images.githubusercontent.com/59369762/196363965-354e3698-5604-47d1-aaaa-973de6e2a50e.png)
Move to the theme.css to style your theme using the data-theme you've set. Forexample
![Screenshot_20221015-100926~2](https://user-images.githubusercontent.com/59369762/196364322-3ba6c2b0-a8dd-4912-aaa1-237fcf918fbe.png)
