### ISSUE TITLE
Add A New Theme (Fire)

### ISSUE THREAD

**Issue by faria-karim-porna** [abel-otegbola/clock-app#62]
Hey, @abel-otegbola I want to add a fire theme on your app. Can I do this? Please assign me the task.

**Comment by abel-otegbola** [comment]
Alright @faria-karim-porna please go ahead

**Comment by abel-otegbola** [comment]
Also, don't forget to star the repo. Thanks

**Comment by abel-otegbola** [comment]
Hi @faria-karim-porna I checked the contributors and discovered that you already added a theme to the project. 
The project is meant to help people get started with open source as such we only allow one pull request per person.

**Comment by faria-karim-porna** [comment]
Got it. Alright.
