### ISSUE TITLE
Adding logo.

### ISSUE THREAD

**Issue by sonejamohit** [abel-otegbola/clock-app#69]
Changes to be made according to the color theme.

**Comment by abel-otegbola** [comment]
Hi @sonejamohit the toggle button is fine as it is but if you think you can make it better, go ahead but know that we aim to keep the design as minimal as possible no extra effects.

**Comment by abel-otegbola** [comment]
Also, make sure you check the current design as I have just updated it recently

**Comment by sonejamohit** [comment]
The button's looking great, and I was suggesting making the similar changes you've made.
I can design a logo for the web app.

**Comment by abel-otegbola** [comment]
Alright. Take reference from the current favicon. Just make something simple.

**Comment by sonejamohit** [comment]
It's done, please have a look.

**Comment by abel-otegbola** [comment]
Already merged it. Thanks @sonejamohit
