### ISSUE TITLE
Make footer social icons same as header social icons

### ISSUE THREAD

**Issue by abel-otegbola** [abel-otegbola/clock-app#74]
Style the footer social icons to be the same as header social icons

**Comment by DPRIYATHAM** [comment]
I am interested to work on this

**Comment by abel-otegbola** [comment]
`go ahead... I've assigned it to you`

**Comment by DPRIYATHAM** [comment]
Done
Created a PR

**Comment by abel-otegbola** [comment]
Thanks for the contribution @DPRIYATHAM

**Comment by DPRIYATHAM** [comment]
Welcome @abel-otegbola
