### ISSUE TITLE
Custom scroll bar with hover effect

### ISSUE THREAD

**Issue by KushalPareek** [abel-otegbola/clock-app#77]
@abel-otegbola   Can I add Custom scroll bar with hover effect?I tried it.You can see this screenshot.
<img width="960" alt="freak" src="https://user-images.githubusercontent.com/105929422/198846115-838a2b0c-907a-4f4f-80f8-7316211d92fd.png">

**Comment by abel-otegbola** [comment]
Go ahead @KushalPareek

**Comment by KushalPareek** [comment]
Thank u so much. I have sent you a Pull Request. Please review it.

**Comment by abel-otegbola** [comment]
Done. Thank you for the contribution.

**Comment by abel-otegbola** [comment]
Don't forget to star the project

**Comment by KushalPareek** [comment]
Definitely sir👍
